requests.exceptions.ConnectionError: HTTPSConnectionPool(host='https', port=443): Max retries exceeded with url: //lp.vk.com/wh204074660?act=a_check&key=61fd4681a6acd72968d3fb0fea0784698cf6db34&ts=9&wait=25&mode=2&version=5.21 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000021DB59AE820>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))